"site_name": "feol"

"columns":
    "kozelet":
        "archive_url_format": "https://www.feol.hu/kozelet/"

    "sport":
        "archive_url_format": "https://www.feol.hu/sport/"

    "kek-hirek":
        "archive_url_format": "https://www.feol.hu/kek-hirek/"

    "orszag-vilag":
        "archive_url_format": "https://www.feol.hu/orszag-vilag/"

    "kultura":
        "archive_url_format": "https://www.feol.hu/kultura/"

    "gazdasag":
        "archive_url_format": "https://www.feol.hu/gazdasag/"


"portal_specific_exctractor_functions_file": "../extractors/site_specific_extractor_functions_news_pgvmt.py"
"extract_next_page_url_fun": "extract_next_page_url_feol"
"extract_article_urls_from_page_fun": "extract_article_urls_from_page_feol"

"next_url_by_pagenum": false
"infinite_scrolling": false
"archive_page_urls_by_date": false
"go_reverse_in_archive": true
"verify_request": true
"ignore_archive_cache": false

# "new_article_url_threshold": 0

"corpus_converter_file": "../extractors/corpus_converters.py"
"corpus_converter": "dummy-converter"
